name: CI Pipeline â€” Feature Login Branch



on:
  push:
    branches:
      - feature-login
  pull_request:
    branches:
      - feature-login

jobs:
  build-and-test-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run login module
        run: |
          echo "Running login.py from FEATURE branch"
          python login.py

      - name: Show config
        run: |
          echo "Printing config.yaml"
          cat config.yaml

      - name: Success message
        run: echo "Feature-login branch pipeline completed successfully ðŸš€"
